### ISSUE TITLE
CUDA Error met during running the script

### ISSUE THREAD

**Issue by yskim5892** [jesbu1/hidio#12]
Hello, I wanted to run and test HIDIO for experiments, so I followed the instruction you've provided
> git clone --recursive https://github.com/jesbu1/hidio
cd hidio
pip install -e . -e alf

and ran
> python -m alf.bin.train --gin_file hierarchical_reacher.gin --root_dir=test

 as described in README.md, but unfortunately met the following error...

> I0118 11:14:52.488085 139735311107264 parallel_environment.py:91] Spawning all processes.
I0118 11:14:52.806012 139735311107264 parallel_environment.py:98] All processes started.
I0118 11:14:52.841016 139735311107264 policy_trainer.py:128] observation_spec=BoundedTensorSpec(shape=(17,), dtype=torch.float32, minimum=array(-inf, dtype=float32), maximum=array(inf, dtype=float32))
I0118 11:14:52.841375 139735311107264 policy_trainer.py:129] action_spec=BoundedTensorSpec(shape=(7,), dtype=torch.float32, minimum=array(-1., dtype=float32), maximum=array(1., dtype=float32))
Skill spec: BoundedTensorSpec(shape=(8,), dtype=torch.float32, minimum=array(-1., dtype=float32), maximum=array(1., dtype=float32))
I0118 11:14:54.858534 139735311107264 sac_algorithm.py:79] Target entropy is calculated for Higher_level_SAC: -7.330325839756005.
W0118 11:14:54.868608 139735311107264 common.py:712] last_kernel_initializer is not specified for the last layer of size 8.
E0118 11:14:54.905147 139735311107264 nest.py:51] map_structure() fails for ([EmbeddingPreprocessor(
  (_embedding_net): EncodingNetwork(
    (_input_preprocessor_modules): ModuleList()
    (_fc_layers): ModuleList(
      (0): FC(
        (_linear): Linear(in_features=51, out_features=128, bias=True)
      )
    )
  )
), EmbeddingPreprocessor(
  (_embedding_net): EncodingNetwork(
    (_input_preprocessor_modules): ModuleList()
    (_fc_layers): ModuleList(
      (0): FC(
        (_linear): Linear(in_features=21, out_features=128, bias=True)
      )
    )
  )
), EmbeddingPreprocessor(
  (_embedding_net): Embedding(4, 128)
), EmbeddingPreprocessor(
  (_embedding_net): EncodingNetwork(
    (_input_preprocessor_modules): ModuleList()
    (_fc_layers): ModuleList(
      (0): FC(
        (_linear): Linear(in_features=8, out_features=128, bias=True)
      )
    )
  )
)], [TensorSpec(shape=(51,), dtype=torch.float32), TensorSpec(shape=(21,), dtype=torch.float32), BoundedTensorSpec(shape=(), dtype=torch.int64, minimum=array(0), maximum=array(3)), BoundedTensorSpec(shape=(8,), dtype=torch.float32, minimum=array(-1., dtype=float32), maximum=array(1., dtype=float32))]). Error message: 'CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`'

There are also some traceback logs, so I'll attach them as well if you want. As far as I've searched, this is maybe due to a size mismatch between layers. However, I double-checked that the code(as well as .gin files) in my repository is identical to yours in this GitHub repository.
Could you tell me how I can deal with this error? Thanks!

**Comment by jesbu1** [comment]
Hi Yoonsung, I tried to reproduce this issue but I could not. I started with a fresh conda environment with python 3.7 and it works fine for me with this exact command. Can you retry the commands in a fresh python 3.7 virtual environment?

In the fresh conda environment I had to upgrade the version of tensorboard `pip install --upgrade tensorflow-gpu` to get rid of a FileNotFound error but other than that I followed the instructions exactly.

**Comment by jesbu1** [comment]
I believe this is caused by some issue with your CUDA install and PyTorch version. Our code uses PyTorch for model training, could you try modifying your PyTorch installation so that it matches your cuda version?

**Comment by yskim5892** [comment]
It's strange because my server works well in other settings.
However, I tried on the other server and it worked fine! :) 
Maybe it was just due to some incompatibility issue with the CUDA installation in my previous server. 
Thanks!

**Comment by jesbu1** [comment]
Great!
